"""key field added

Revision ID: 70741a32d0a2
Revises: 5a3f89a237bc
Create Date: 2021-06-25 23:04:28.791257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70741a32d0a2'
down_revision = '5a3f89a237bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'key')
    # ### end Alembic commands ###
